exclude:
  - "/vendor/"
  - "/node_modules/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: karlstatik
subtitle: "büro für tragwerksplanung"
url: "https://karlstatik.de" # the base hostname & protocol for your site
baseurl: "/website"
logo: "/img/logo.svg"
lang: de

# Build settings
markdown: kramdown

collections:
  leistungen:
    output: true
